# retrieve cloudflare token from vault and create secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-token # EDIT
    template:
      engineVersion: v2
      data:
        token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: secret/k8s # secret path
        property: CLOUDFLARE # secret key
