apiVersion: v1
kind: Secret
metadata:
  name: argocd-tls
  namespace: argocd
type: Opaque
data:
  token: "dGVzdAo="  # Base64 encoded value of CLOUDFLARE TOKEN
  user: "dGVzdAo="   # Base64 encoded value of USERNAME
