apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.name }}
  namespace: {{ .Values.namespace }}
data:
  prometheus-config.json: |
    {{- .Files.Get "prometheus-config.json" | nindent 4 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.prometheus.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.prometheus.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.name }}
    spec:
      containers:
        - name: {{ .Values.prometheus.name }}
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: {{ .Values.prometheus.service.targetPort }}
          volumeMounts:
            - name: {{ .Values.prometheus.name }}
              mountPath: /etc/prometheus/prometheus-config.json
              subPath: prometheus-config.json
          command:
            - "/bin/prometheus"
            - "--config.file=/etc/prometheus/prometheus-config.json"
      volumes:
        - name: {{ .Values.prometheus.name }}
          configMap:
            name: {{ .Values.prometheus.name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.prometheus.name }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.targetPort }}