apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todoapp
resources:
  - namespace.yaml
  - app/deployment.yaml
  - app/istio.yaml
  - mongodb/deployment.yaml
  - monitoring/grafana-deployment.yaml
  - monitoring/prometheus-deployment.yaml