apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp
  namespace: taskapp
  labels:
    app: taskapp
    release: primary
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: taskapp
      release: primary
  template:
    metadata:
      labels:
        app: taskapp
        release: primary
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: taskapp
          image: ghcr.io/dstoecklein/taskapp:v0.0.12
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
      #imagePullSecrets:  
      #        - name: ghcr
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: taskapp
  namespace: taskapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taskapp
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
