apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: taskapp
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - follow_redirects: true
          enable_http2: true
          scheme: http
          timeout: 10s
          api_version: v2
          static_configs:
            - targets: []
    scrape_configs:
      - job_name: prometheus
        honor_timestamps: true
        scrape_interval: 15s
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        follow_redirects: true
        static_configs:
          - targets:
              - localhost:9090
      - job_name: "taskapp"
        scrape_interval: 10s
        metrics_path: /metrics
        static_configs:
          - targets: ["taskapp:8000"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: taskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yaml
              subPath: prometheus.yaml
          command:
            - "/bin/prometheus"
            - "--config.file=/etc/prometheus/prometheus.yaml"
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: taskapp
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
