apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: taskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana
          persistentVolumeClaim:
            claimName: grafana

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: taskapp
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: taskapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi