apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
helmCharts:
  - name: cert-manager
    version: v1.18.2
    namespace: cert-manager
    repo: https://charts.jetstack.io
    valuesInline:
      installCRDs: true
resources:
  - namespace.yaml
  - cert-manager.yaml
