namespace: todoapp

nameOverride: ""

todoapp:
  release: primary
  image:
    repository: ghcr.io/arodindev/todoapp
    version: "" # use appVersion from Chart spec
    pullPolicy: Always
  readinessProbe:
    healthEndpoint: /api/v1/healthz
    initialDelaySeconds: 5
  hpa:
    minReplicas: 1
    maxReplicas: 1
  service:
    port: 80
    targetPort: 8000

istio:
  host: todoapp.arodindev.com
  
mongo:
  name: mongo
  release: primary
  image:
    repository: mongo
    tag: latest 
    pullPolicy: IfNotPresent
  persistentVolume:
    accessMode: ReadWriteOnce
  service:
    port: 27017
    targetPort: 27017

