# Backend 'taskapp' with live update
docker_build('ghcr.io/dstoecklein/taskapp', './backend',
    live_update=[
        sync('./backend', '/app'),
        run("cd /app && pip install -r  requirements.txt", trigger="./backend/requirements.txt")
    ]
)
k8s_yaml('k8s/taskapp/backend-deployment.yaml')
k8s_resource('taskapp', port_forwards=8000)

# Frontend 'taskapp-frontend' with live update
docker_build('ghcr.io/dstoecklein/taskapp-frontend', './frontend',
    live_update=[
        sync('./frontend', '/app'),
        run("cd /app && npm install --production", trigger=["./frontend/package.json", "./frontend/package-lock.json"])
    ]
)
k8s_yaml('k8s/taskapp/frontend-deployment.yaml')
k8s_resource('taskapp-frontend', port_forwards=3000)

# Prometheus
k8s_yaml('k8s/monitoring/prometheus-deployment.yaml')
k8s_resource('prometheus', port_forwards=9090)

# Grafana
k8s_yaml('k8s/monitoring/grafana-deployment.yaml')
k8s_resource('grafana', port_forwards=8001)