apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-frontend
    release: {{ .Values.taskapp.release }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
      release: {{ .Values.taskapp.release }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
        release: {{ .Values.taskapp.release }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.taskapp.image.repository }}{{ .Release.Name }}-frontend:{{ default .Chart.AppVersion .Values.taskapp.image.version }}"
          ports:
            - containerPort: {{ .Values.taskapp.service.targetPortFrontend }}
          imagePullPolicy: {{ .Values.taskapp.image.pullPolicy }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
      #imagePullSecrets:  
      #        - name: ghcr
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-frontend
  minReplicas: {{ .Values.taskapp.hpa.minReplicas }}
  maxReplicas: {{ .Values.taskapp.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
