apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.grafana.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.grafana.name }}
    spec:
      containers:
        - name: {{ .Values.grafana.name }}
          image: {{ .Values.grafana.image.repository }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: {{ .Values.grafana.service.targetPort }}
          volumeMounts:
            - name: {{ .Values.grafana.name }}
              mountPath: /var/lib/grafana
      volumes:
        - name: {{ .Values.grafana.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.grafana.name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.grafana.name }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.targetPort }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi